#spring configure
spring:
  profiles:
    active: dev
  freemarker:
    #freemarker默认后缀为.ftl  修改为.html
    suffix: .html
  aop:
    # Whether subclass-based (CGLIB) proxies are to be created (true) asopposed to standard Java interface-based proxies (false).
    proxy-target-class: false
    #Add @EnableAspectJAutoProxy.
    auto: true
  #springboot 热部署工具
  devtools:
    restart:
      #热部署，修改代码后不重启，默认为true重启
      enabled: true


springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
  packages-to-scan: com.stylesmile.modules
kni
logging:
  level:
    com.stylesmile: debug
    org.springdoc: debug
